site_name: Beam Documentation
theme: readthedocs
theme_dir: docs/theme
pages:
  - Home: 'index.md'
  - Frequently Asked Questions: 'about/faq.md'
  - User Guide:
      - 'Getting Started': 'user-guide/getting-started.md'
      - 'Models': 'user-guide/models.md'
      - 'Databases': 'user-guide/databases.md'
      - 'Basic Queries': 'user-guide/queries/basic.md'
      - 'More complex SELECTs': 'user-guide/queries/select.md'
      - 'Ordering': 'user-guide/queries/ordering.md'
      - 'Relationships': 'user-guide/queries/relationships.md'
      - 'Aggregates': 'user-guide/queries/aggregates.md'
      - 'Combining queries': 'user-guide/queries/combining-queries.md'
#      - 'Common data types': 'user-guide/queries/data-types.md'
      - 'Window functions': 'user-guide/queries/window-functions.md'
      - 'Advanced features': 'user-guide/queries/advanced-features.md'
  - Schema management:
      - 'The Migrations Framework': 'schema-guide/migrations.md'
      - 'The beam-migrate tool': 'schema-guide/tool.md'
      - 'Supported migrations': 'schema-guide/supported.md'
  - Backends:
      - 'beam-postgres': 'user-guide/backends/beam-postgres.md'
      - 'beam-sqlite': 'user-guide/backends/beam-sqlite.md'
      - 'Writing a Custom Backend': 'user-guide/custom-backends.md'
  - Reference:
      - 'Models': 'reference/models.md'
      - 'Expressions': 'reference/expression.md'
      - 'Queries': 'reference/queries.md'
      - 'Extending': 'reference/extensibility.md'
  - About:
      - 'Compatibility Matrix': 'about/compatibility.md'
      - 'License': 'about/license.md'
      - 'Release Notes': 'about/release-notes.md'
markdown_extensions:
  - admonition
  - docs.markdown.beam_query:
      template_dir: 'docs/beam-templates'
      cache_dir: 'docs/.beam-query-cache'
  - markdown_fenced_code_tabs
