version: 2
jobs:
  build:
    docker:
      - image: nixorg/nix:circleci
        environment:
          SSL_CERT_FILE: /etc/ssl/certs/ca-bundle.crt
    steps:
      - restore_cache:
          keys:
            - deps-{{ .Branch }}-{{ .Revision }}
            - deps-{{ .Branch }}
            - deps-
      - run:
          name: Update nixpkgs
          command: "nix-channel --add https://nixos.org/channels/nixos-18.09 nixpkgs && nix-channel --update && nix-channel --list"
      - run:
          name: Update nix
          command: "nix-env -u nix"
      - checkout
      - run:
          name: Build stack
          command: "nix-build -A stack '<nixpkgs>' -o stack-bin"
      - run:
          name: Build deps
          command: ./stack-bin/bin/stack --no-terminal --nix --nix-shell-file=./shell.nix build --dependencies-only --resolver lts-12.0
          no_output_timout: 30mx
      - save_cache:
          key: deps-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".stack-work"
      - run:
          name: Build
          command: ./stack-bin/bin/stack --no-terminal --nix --nix-shell-file=./shell.nix build --flag beam-core:werror --flag beam-sqlite:werror --flag beam-postgres:werror --flag beam-migrate:werror --resolver lts-12.0
      - run:
          name: Test
          command: ./stack-bin/bin/stack --no-terminal --nix --nix-shell-file=./shell.nix test --flag beam-core:werror --flag beam-sqlite:werror --flag beam-postgres:werror --flag beam-migrate:werror --resolver lts-12.0
